# ============================================================
#  BCH2 JARVIS NODE – Production Config
# ============================================================

# --- Network ---
listen=1
port=8339
maxconnections=64
dnsseed=1

# --- RPC ---
server=1
rpcuser=jarvis
rpcpassword=xz8A1Grk9NAKk4l2QerGwCmcwtVoGh62
rpcport=8342
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcallowip=172.16.0.0/12
rpcallowip=192.168.0.0/16
rpcallowip=10.0.0.0/8

# --- Performance ---
dbcache=1024
maxmempool=400
mempoolexpiry=72

# --- Indexing ---
txindex=1
blockfilterindex=1

# --- Wallet (Holding Address) ---
disablewallet=0

# --- Logging ---
printtoconsole=1
debug=0
logtimestamps=1
